# Generated by Django 6.0.4 on 2026-05-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='number',
        ),
    ]
