# Generated by Django 6.0.4 on 2026-05-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patientprofile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='role',
            new_name='patient_type',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='program',
            field=models.CharField(blank=True, choices=[('CS', 'CS'), ('IT', 'IT'), ('SE', 'SE'), ('BIT', 'BIT')], max_length=20, null=True),
        ),
    ]
