# Generated by Django 6.0.4 on 2026-05-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_role_patientprofile_patient_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='patient_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('UNIVERSITY_STAFF', 'University Staff'), ('CLINIC_STAFF', 'Clinic Staff')], default='STUDENT', max_length=20),
        ),
    ]
