# Generated by Django 6.0.4 on 2026-05-02 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patientprofile_patient_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_CONSULTATION', 'In Consultation'), ('LAB', 'Lab'), ('PHARMACY', 'Pharmacy'), ('COMPLETE', 'Complete')], default='WAITING', max_length=20)),
                ('queue_position', models.IntegerField(blank=True, null=True)),
                ('queue_category', models.CharField(blank=True, choices=[('SEVERE', 'Severe'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor')], max_length=10, null=True)),
                ('other_symptoms', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_visits', to='patients.symptom')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_symptoms', to='patients.visit')),
            ],
            options={
                'unique_together': {('visit', 'symptom')},
            },
        ),
    ]
