# Generated by Django 6.0.4 on 2026-05-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_symptom_visit_visitsymptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
