# Generated by Django 6.0.4 on 2026-05-07 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_staff', '0001_initial'),
        ('patients', '0006_patientprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('severity_override', models.CharField(blank=True, choices=[('SEVERE', 'Severe'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor')], max_length=10, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('consulted_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='clinic_staff.clinicstaff')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='patients.visit')),
            ],
            options={
                'ordering': ['-consulted_at'],
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests_requested', models.TextField(help_text='Doctor types all tests needed e.g. Malaria RDT, FBC, Typhoid')),
                ('notes_to_lab', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_request', to='consultation.consultation')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(help_text='Lab attendant writes all results here')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lab_attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='clinic_staff.clinicstaff')),
                ('lab_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='consultation.labrequest')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('dispense_status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPENSED', 'Dispensed')], default='PENDING', max_length=10)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultation.consultation')),
                ('pharmacist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to='clinic_staff.clinicstaff')),
            ],
            options={
                'ordering': ['-prescribed_at'],
            },
        ),
    ]
