# Generated by Django 6.0.4 on 2026-05-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=50, null=True)),
                ('input_type', models.CharField(choices=[('BOOLEAN', 'Positive/Negative'), ('NUMBER', 'Numeric value'), ('TEXT', 'Free text')], default='TEXT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
