# Generated by Django 6.0.4 on 2026-05-02 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('staff_type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('LAB_ATTENDANT', 'Lab Attendant'), ('ADMIN', 'Admin')], max_length=20)),
                ('specialization', models.CharField(blank=True, choices=[('GENERAL_MEDICINE', 'General Medicine'), ('DENTAL', 'Dental'), ('PHARMACY', 'Pharmacy'), ('LABORATORY', 'Laboratory'), ('NURSING', 'Nursing'), ('ADMINISTRATION', 'Administration')], max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinicstaff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinic Staff',
                'verbose_name_plural': 'Clinic Staff',
            },
        ),
    ]
