# Generated by Django 6.0.4 on 2026-05-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ClinicStaff',
        ),
    ]
