# Generated by Django 6.0.4 on 2026-05-09 10:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('MORNING', 'Morning Shift'), ('AFTERNOON', 'Afternoon Shift'), ('NIGHT', 'Night Shift')], default='MORNING', max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['DOCTOR', 'NURSE', 'LAB_ATTENDANT', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]
