# Generated by Django 6.0.4 on 2026-05-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('LAB_ATTENDANT', 'Lab Attendant'), ('ADMIN', 'Admin'), ('PHARMACIST', 'Pharmacist')], default='PATIENT', max_length=20),
        ),
    ]
