# Generated by Django 6.0.4 on 2026-05-07 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('TABLETS', 'Tablets'), ('CAPSULES', 'Capsules'), ('BOTTLES', 'Bottles'), ('VIALS', 'Vials'), ('SACHETS', 'Sachets')], default='TABLETS', max_length=20)),
                ('low_stock_threshold', models.IntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_updates', to='clinic_staff.clinicstaff')),
            ],
            options={
                'ordering': ['medicine_name'],
            },
        ),
    ]
