# Generated by Django 6.0.4 on 2026-05-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinestock',
            name='avg_duration',
            field=models.FloatField(default=7.0, help_text='Average prescription duration in days'),
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='avg_frequency',
            field=models.FloatField(default=3.0, help_text='Average doses per day'),
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='avg_monthly_rx',
            field=models.FloatField(default=10.0, help_text='Average prescriptions per month'),
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='avg_monthly_units',
            field=models.FloatField(default=30.0, help_text='Average units dispensed per month'),
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='last_restocked',
            field=models.DateField(blank=True, help_text='Date last restocked', null=True),
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='medical_condition',
            field=models.CharField(blank=True, help_text='Linked disease e.g. Malaria', max_length=200),
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='reorder_threshold',
            field=models.IntegerField(default=50, help_text='Reorder when stock falls below this'),
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='unit_cost',
            field=models.FloatField(default=0.0, help_text='Cost per unit in UGX'),
        ),
    ]
