# Generated by Django 6.0.4 on 2026-05-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicinestock_avg_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinestock',
            name='unit_cost',
        ),
    ]
